"""PRIVIA shared types.

Every cross-boundary payload in PRIVIA is defined here exactly once, so the
backend, the agent, the tools and the desktop client cannot drift apart.
"""

from __future__ import annotations

from .agent import (
    AgentRun,
    ChatRequest,
    ChatResponse,
    Classification,
    Entity,
    PhaseRecord,
    Plan,
    PlanStep,
    Verification,
    VerificationCheck,
)
from .base import OpenModel, PriviaModel
from .domain import (
    AuditEvent,
    CalendarEvent,
    CommandInspection,
    CommandResult,
    EmailAddress,
    EmailAttachment,
    EmailDraft,
    EmailMessage,
    FileContent,
    FileEntry,
    FileMetadata,
    HealthReport,
    IntegrationInfo,
    MemoryRecord,
    ModelInfo,
    Note,
    PageContent,
    PrivacyState,
    SearchResult,
)
from .enums import (
    AgentPhase,
    AuditAction,
    ErrorCode,
    IntegrationStatus,
    Intent,
    MemoryKind,
    MessageRole,
    PermissionDecision,
    PermissionGrantState,
    ProcessingLocation,
    RiskLevel,
    RunStatus,
    Scope,
)
from .errors import (
    BadRequestError,
    CloudDisabledError,
    CommandNotAllowedError,
    ConfigurationError,
    ConfirmationRequiredError,
    ConflictError,
    IntegrationUnavailableError,
    LLMInvalidOutputError,
    LLMUnavailableError,
    NotFoundError,
    PathNotAllowedError,
    PathTraversalError,
    PayloadTooLargeError,
    PermissionDeniedError,
    PriviaError,
    PromptInjectionError,
    RateLimitedError,
    SecurityError,
    SsrfBlockedError,
    SttUnavailableError,
    ToolError,
    ToolInvalidArgumentsError,
    ToolNotFoundError,
    ToolOutputTooLargeError,
    ToolTimeoutError,
    TtsUnavailableError,
    UnauthorizedError,
    UrlNotAllowedError,
    ValidationError,
)
from .ids import new_id, ulid, utcnow, utcnow_iso
from .observability import LogRecord, MetricSnapshot
from .permissions import (
    PermissionGrant,
    PermissionPrompt,
    PermissionUpdate,
    PolicyRequest,
    PolicyResult,
)
from .tools import (
    ConfirmationRequest,
    ConfirmationResponse,
    RetryPolicy,
    ToolCall,
    ToolResult,
    ToolSpec,
)

__version__ = "1.0.0"

__all__ = [
    "__version__",
    # base
    "PriviaModel",
    "OpenModel",
    # enums
    "AgentPhase",
    "AuditAction",
    "ErrorCode",
    "Intent",
    "IntegrationStatus",
    "MemoryKind",
    "MessageRole",
    "PermissionDecision",
    "PermissionGrantState",
    "ProcessingLocation",
    "RiskLevel",
    "RunStatus",
    "Scope",
    # ids
    "new_id",
    "ulid",
    "utcnow",
    "utcnow_iso",
    # errors
    "PriviaError",
    "BadRequestError",
    "ValidationError",
    "UnauthorizedError",
    "NotFoundError",
    "ConflictError",
    "RateLimitedError",
    "PayloadTooLargeError",
    "ConfigurationError",
    "ToolError",
    "ToolNotFoundError",
    "ToolInvalidArgumentsError",
    "ToolTimeoutError",
    "ToolOutputTooLargeError",
    "PermissionDeniedError",
    "ConfirmationRequiredError",
    "SecurityError",
    "PathNotAllowedError",
    "PathTraversalError",
    "CommandNotAllowedError",
    "UrlNotAllowedError",
    "SsrfBlockedError",
    "PromptInjectionError",
    "LLMUnavailableError",
    "LLMInvalidOutputError",
    "CloudDisabledError",
    "SttUnavailableError",
    "TtsUnavailableError",
    "IntegrationUnavailableError",
    # tools
    "ToolSpec",
    "ToolCall",
    "ToolResult",
    "RetryPolicy",
    "ConfirmationRequest",
    "ConfirmationResponse",
    # permissions
    "PermissionGrant",
    "PermissionPrompt",
    "PermissionUpdate",
    "PolicyRequest",
    "PolicyResult",
    # agent
    "AgentRun",
    "ChatRequest",
    "ChatResponse",
    "Classification",
    "Entity",
    "Plan",
    "PlanStep",
    "PhaseRecord",
    "Verification",
    "VerificationCheck",
    # domain
    "FileEntry",
    "FileMetadata",
    "FileContent",
    "Note",
    "CalendarEvent",
    "EmailAddress",
    "EmailAttachment",
    "EmailMessage",
    "EmailDraft",
    "SearchResult",
    "PageContent",
    "CommandInspection",
    "CommandResult",
    "MemoryRecord",
    "AuditEvent",
    "IntegrationInfo",
    "ModelInfo",
    "PrivacyState",
    "HealthReport",
    # observability
    "LogRecord",
    "MetricSnapshot",
]
